### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by lazerkat** [mikaelkristiansson/react-theme-vscode#2]
Currently, there's no LICENSE file contained in the repo. This essentially prevents anybody from using the code in this repo for (almost?) all purposes (see https://github.com/github/choosealicense.com/issues/196).

React itself is licensed under MIT, so perhaps that would make the most sense for this repo.

**Comment by mikaelkristiansson** [comment]
Great suggestion! I just added it. 👍
